name: Run UI Tests

on:
  push:
    branches: [ main ]
  pull_request:


jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirement.txt

    - name: Run UI tests
      run: |
        pytest ui-testing/tests/ -v --alluredir=ui-testing/allure-results

    - name: Install Allure commandline
      run: |
        npm install -g allure-commandline

    - name: Generate Allure Report
      run: |
        allure generate ./ui-testing/allure-results -o ./ui-testing/allure-report --clean

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: ui-allure-report
        path: ui-testing/allure-report
